from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
ARTIFACTS_DIR = BASE_DIR / "artifacts"
CASCADE_PATH = str(BASE_DIR / "artifacts" / "haarcascade_frontalface_default.xml")
MODEL_PATH = str(ARTIFACTS_DIR / "recognizer.joblib")
CALIBRATION_PATH = str(ARTIFACTS_DIR / "calibration.json")
DB_PATH = str(BASE_DIR / "database" / "attendance.db")
EMBEDDING_DIM = 128
STABILITY_FRAMES = 5
COSINE_THRESHOLD = 0.42
FACE_DISTANCE_THRESHOLD = 0.50
FACE_DISTANCE_MARGIN = 0.04
DEEPFACE_COSINE_THRESHOLD = 0.68
ORB_COSINE_THRESHOLD = 0.80
COSINE_MARGIN = 0.05
MIN_MARK_CONFIDENCE = 78.0
MIN_SAMPLES_PER_STUDENT = 4
CAPTURE_MIN_FACE_WIDTH = 100
CAPTURE_MIN_FACE_HEIGHT = 100
CAPTURE_MIN_SHARPNESS = 55.0
CLASSIFIER_MIN_PROB = 0.62
CLASSIFIER_STRONG_PROB = 0.78
ATTENDANCE_COOLDOWN_SECONDS = 60

ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
